[package]
name = "snorkel"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "simple_loop"
path = "bin/simple_loop.rs"

[[bin]]
name = "timerfd"
path = "bin/timerfd.rs"

[dependencies]
crossterm = "0.26.1"
portmidi = "0.2.6"
rosc = "0.8.1"
nom = "7.1.3"
tui = "0.19.0"
spin_sleep = "1.1.1"
libc = "0.2.139"
ndhistogram = "0.8.0"
timerfd = "1.4.0"
ropey = "1.6.0"